apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepositary
    name: flux-system
  path: ./apps/overlays/staging
