apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: kong1
  namespace: kong1
spec:
  intrevel: 5m
  chart:
    spec:
      chart: kong
      version: 2.32.0
      sourceRef:
        kind: HelmRepository
        name: kong1
        namespace: kong1
      intreval: 1m
  values:
    image:
      repository: kong/kong-gateway
      tag: "3.4.3.11"
    replicationCount: 3
